apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: "" # TO DO vault endpoint
      path: "secret"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "" # TO DO secret with vault token
          key: "" # TO DO key of value